[workspace]

members = [
  "crates/drydoc",
  "crates/drydoc-gen",
  "crates/drydoc-dev",
  "crates/drydoc-serve",
  "crates/drydoc-model",
  "crates/drydoc-ipc",
  "crates/drydoc-pkg",
  "crates/drydoc-pkg-manager",
]