[package]
name = "drydoc-serve"
version = "0.1.0"
authors = ["Semio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = [ "full" ] }
warp = "0.2.5"
clap = "3.0.0-beta.2"
